#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'anagram' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def countUnique(s):
    return {char: s.count(char) for char in set(s)}
    
def anagram(s):
    # Write your code here
    if len(s) % 2 != 0:
        return -1
    
    mid = len(s)// 2
    s1 = s[:mid]
    s2 = s[mid:]
    s1_count = countUnique(s1) 
    s2_count = countUnique(s2)
    
    count = 0
        
    for char in s1_count:
        if s1_count[char] > s2_count.get(char,0):
            count += s1_count[char] - s2_count.get(char,0)
                
    return count
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = anagram(s)

        fptr.write(str(result) + '\n')

    fptr.close()
