#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'balancedSums' function below.
#
# The function is expected to return a STRING.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def balancedSums(arr):
    # Write your code here
    total_sum = sum(arr) 
    left = 0
    string = 'NO'
    
    for x in arr:  #instead of summing the spliced lists every iteration, its better to get the total sum before hand
        right = total_sum - left - x  #we can find the current running sum of the left and right side of the current index with this
        if left == right:
            string = 'YES'
        left += x
    
    return string

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    T = int(input().strip())

    for T_itr in range(T):
        n = int(input().strip())

        arr = list(map(int, input().rstrip().split()))

        result = balancedSums(arr)

        fptr.write(result + '\n')

    fptr.close()
